" stuff for Vundle (vim package manager)
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
"
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'Chiel92/vim-autoformat'
"Plugin 'OmniSharp/omnisharp-vim'
Plugin 'lervag/vimtex'

Plugin 'Shougo/neocomplcache'
Plugin 'Raimondi/delimitMate'
Plugin 'ervandew/supertab'

Plugin 'gucio321/libremath-vim'

Plugin 'rust-lang/rust.vim'

"Plugin 'Valloric/YouCompleteMe'
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line



"============================================
"colors listed
"============================================
"color elflord
"color darkblue
"color evening
"color desert
"color default
"
"color delek
"
"color industry
color koehler
"color murphy
"#ten wyrzej jest całkiem fajny
"color pablocolor slate
"color slate
"tez niezly
"set number
"call plug#begin('~/.vim/bundle')
"call plug#end()

"rust.vim
syntax enable
filetype plugin indent on

"VIMTEX
let g:tex_flavor='latex'
let g:vimtex_view_method='okular'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

"let libremath = "~/.vim/mysyntax/ibremath.vim"
"au BufRead,BufNewFile *.lm set filetype=libremath
"au! Syntax libremath source ~/.vim/mysyntax/ibremath.vim




set nowrap
"set loadplugins
"
"
"
"python
"let g:python3_host_prog=/usr/bin/python3
"Plugin 'Chiel92/vim-autoformat'
"

" for autoformat (c++)
" au BufWrite * :Autoformat
let b:formatdef_custom_cpp='"clang-format --style=LVM"'
let b:formatters_cpp = ['custom_cpp']
let b:formatdef_custom_yml='""'
let b:formatters_yml = ['custom_yml']
let b:formatdef_custom_ino='"clang-format --style=Google"'
let b:formatters_ino= ['custom_ino']

let g:go_fmt_command = "/home/mszeptuch/go/bin/gofumpt"
let g:go_fmt_options = {
                        \ 'goimports': '-local mycompany.com',
                        \ }

" https://github.com/fuh/vimrc/blob/master/vimrc
"Plugin 'garbas/vim-snipmate'
"Plugin 'honza/vim-snippets'
"Plugin 'MarcWeber/vim-addon-mw-utils'
"Plugin 'tomtom/tlib_vim'
"Plugin 'jwhitley/vim-matchit'
"Plugin 'Lokaltog/vim-easymotion'
"Plugin 'tpope/vim-surround'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'sjl/gundo.vim'
"Plugin 'godlygeek/tabular'
"Plugin 'nathanaelkane/vim-indent-guides'
"Plugin 'tpope/vim-markdown'

set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
syntax on
set incsearch
set ignorecase
set smartcase
set history=1000
set nocompatible
set nofoldenable                                                  " disable folding"
set backspace=indent,eol,start                                    " More powerful backspacing
set t_Co=256                                                      " Explicitly tell vim that the terminal has 256 colors "
"set mouse=a                                                       " use mouse in all modes
set nowrap                                                        " dont wrap lines
set showmatch                                                     " show matching bracket (briefly jump)
set showcmd                                                       " show typed command in status bar
set title                                                         " show file in titlebar
"set laststatus=2                                                  " use 2 lines for the status bar
set matchtime=2                                                   " show matching bracket for 0.2 seconds
set autoindent
set expandtab       " expand tab to space
set smartindent     " indent when
set tabstop=8       " tab width
set softtabstop=8   " backspace
set shiftwidth=8    " indent width
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120

" NeoComplCache
let g:neocomplcache_enable_at_startup=1
let g:neoComplcache_disableautocomplete=1
let g:neocomplcache_enable_underbar_completion = 1
let g:neocomplcache_enable_camel_case_completion = 1
let g:neocomplcache_enable_smart_case=1
let g:neocomplcache_min_syntax_length = 3
let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'
set completeopt-=preview

imap <C-k> <Plug>(neocomplcache_snippets_force_expand)
smap <C-k> <Plug>(neocomplcache_snippets_force_expand)
imap <C-l> <Plug>(neocomplcache_snippets_force_jump)
smap <C-l> <Plug>(neocomplcache_snippets_force_jump)

" Useful Functions
"------------------
" easier navigation between split windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" w!! to sudo & write a file
cmap w!! %!sudo tee >/dev/null %

" eggcache vim
nnoremap ; :
:command W w
:command WQ wq
:command Wq wq
:command Q q
:command Qa qa
:command QA qa

" for libremath custom syntax
"let libremath = "~/.vim/mysyntax/ibremath.vim"
"au BufRead,BufNewFile *.lm set filetype=libremath
"au! Syntax libremath source ~/.vim/mysyntax/ibremath.vim

" https://www.thegeekstuff.com/2009/01/tutorial-make-vim-as-your-cc-ide-using-cvim-plugin/
filetype plugin on
